version: 2

sources:
  - name: nhl_api_source
    database: NHL_DB
    schema: RAW

    freshness:
      warn_after: {count: 2, period: day}
    
    loaded_at_field: "to_timestamp(partition_date)"
    
    tables:
      - name: nhl_api_game_events
        description: Data loaded by upstream dagster pipeline. The data is sourced from the NHL REST API https://statsapi.web.nhl.com